version: '3.2'
volumes:
  gem_dir:
services:
  api:
    image: ruby:2.5.1
    working_dir: /srv/app
    command: bin/start
    environment:
      BUNDLE_PATH: /gems
    ports:
    - '12345:9292'
    volumes:
    - gem_dir:/gems
    - ./:/srv/app
  database:
    image: postgres:10.5
